spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zoo
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    format:
      date: iso

