services:
  neo4j:
    image: neo4j:4.2.3
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./export/neo4j/data:/data
      - ./export/neo4j/var/lib/neo4j/conf:/var/lib/neo4j/conf
      - ./export/neo4j/var/lib/neo4j/import:/var/lib/neo4j/import
      - ./export/neo4j/plugins:/plugins
    environment:
      - NE04J_AUTH=neo4j/password